### ISSUE TITLE
UNIONFIND

### ISSUE THREAD

**Issue by chessai** [chessai/diet#17]
https://www.geeksforgeeks.org/union-find/

@andrewthad @andrewthad

**Comment by chessai** [comment]
data-partition       #: Disjoint set (union-find) data structure
        disjoint-sets-st     #: Imperative ST/IO based disjoint sets
        disjoint-containers  #: Containers based on disjoint sets
        union-find           #: A basic union-find data structure
        equivalence          #: A union-find data structure on top of STT

**Comment by chessai** [comment]
almost all operations on this would be O(\alpha(n)) where alpha(n) = 1/ackerman(n) (meaning nearly constant time for all operations), however, for unions, we could get O(log log n), because we won't know what to union up front (a prerequisite for getting O(\alpha(n)))

**Comment by andrewthad** [comment]
I'm not totally sure how this relates to diet sets, but in my mind, the best implementation of disjoint sets would use linear types. That way, you would get the optimal asymptotics described in all the literature (using in-place mutation) but without having to rely on the user to use it in a linear fashion.

**Comment by chessai** [comment]
will linear types drop by 8.6.1? also, if you view each interval as a set with two elements, then unionfind seems very fitting

**Comment by chessai** [comment]
is there a branch of GHC with linear types under development? If so, it might be worth it to get a head start

**Comment by andrewthad** [comment]
Linear types will likely be in 8.6.1. I'm still not convinced on the applicability on unionfind in this scenario. Namely, there are additional invariants:

- All set have at most two elements.
- Sets cannot overlap in their range
- Sets cannot be "adjacent"

Here's tweag's branch: https://github.com/tweag/ghc/tree/linear-types. There's also a `wip-linear-types` branch, but this one looks like it has fewer commits. Read the instructions. They provide a prebuilt docker image for use with stack. This is the only way I've ever tried it out.

**Comment by chessai** [comment]
Sets cannot be adjacent.

**Comment by chessai** [comment]
I think the adjacent issue works out in our favour in disjoint sets. also, I don't think it would be hard to ensure that each set had at most two elements. recall that this implementation of unionfind would be from-scratch.

**Comment by chessai** [comment]
I wrote a library for doing interval calculus (and performs composition of combinators) but I don't think I pushed it to GitHub
