### ISSUE TITLE
Testing for correctness of Foldable instance of Set

### ISSUE THREAD

**Issue by andrewthad** [chessai/diet#2]
I just pushed https://github.com/andrewthad/quickcheck-classes/commit/5140ff215ffc0ce9177513c3cf371e3f2765e2a1, which even tests that the strictness of `foldl'` and `foldr'` is correct. You may want to use it to check `Set`'s `Foldable` instance. There's a way you can use it to check the behavior of the interval set functions as well. I'll show you that in person tomorrow though.

**Comment by chessai** [comment]
ok

**Comment by chessai** [comment]
Haven't tested these yet
